# Generated by Django 5.2.6 on 2025-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='volunteers/profile_photos/'),
        ),
    ]
