# Generated by Django 5.2.6 on 2025-09-04 18:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_volunteer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload a profile picture for ID card', null=True, upload_to=app.models.Volunteer.volunteer_photo_path),
        ),
    ]
